/* HISTORY V33.0 — interactive history dashboard */
(function(){
  'use strict';
  var B=window.__ROSTER_HISTORY_V33__;if(!B)return;
  var page=1,pageSize=5,records=[],filtered=[],recentAll=false,auditAll=false;
  var MONTHS=B.months||[];
  function $(id){return document.getElementById(id)}
  function esc(v){return B.escape?B.escape(String(v==null?'':v)):String(v==null?'':v)}
  function pad(n){return String(n).padStart(2,'0')}
  function pct(n,d){return d?Math.round(n/d*100):0}
  function workflowStatus(d){if(d&&d.workflow&&d.workflow.locked)return 'locked';var s=d&&d.workflow&&d.workflow.status||'draft';return s}
  function statusLabel(s){return {locked:'ล็อกแล้ว',approved:'อนุมัติแล้ว',submitted:'ส่งตรวจแล้ว',draft:'ร่างตาราง'}[s]||s}
  function findAudit(d,words){var a=d&&d.workflow&&Array.isArray(d.workflow.audit)?d.workflow.audit:[];for(var i=0;i<a.length;i++){var x=a[i],t=String(x.action||'');if(words.some(function(w){return t.indexOf(w)>=0}))return x}return null}
  function unitName(){var u=B.getUnit?B.getUnit():{};return u.name||'หน่วยงานหลัก'}
  function schedulerName(d){var a=d&&d.workflow&&Array.isArray(d.workflow.audit)?d.workflow.audit:[];for(var i=0;i<a.length;i++){if(a[i].user)return a[i].user}var u=B.getUnit?B.getUnit():{};return u.scheduler||'ผู้จัดตารางเวร'}
  function noteFor(d){var s=workflowStatus(d);if(s==='locked')return 'ตารางประจำเดือน';if(s==='approved')return 'อนุมัติแล้ว';if(s==='submitted')return 'รออนุมัติ';return 'ร่างแรก'}
  function buildRecords(){records=[];var years=B.getAvailableYears?B.getAvailableYears():[B.getCurrent().year];years.forEach(function(y){var arr=B.getYearRecords(y)||[];arr.forEach(function(r){var d=r.data||{},ap=findAudit(d,['อนุมัติ']),lk=findAudit(d,['ล็อก']),sv=d.savedAt?{at:d.savedAt}:findAudit(d,['บันทึก']);records.push({year:y,month:r.month,data:d,status:workflowStatus(d),unit:unitName(),scheduler:schedulerName(d),savedAt:sv&&sv.at||d.savedAt||'',approvedAt:ap&&ap.at||'',lockedAt:lk&&lk.at||'',note:noteFor(d)})})});records.sort(function(a,b){return String(b.savedAt||'').localeCompare(String(a.savedAt||''))})}
  function setupFilters(){var ys=$('historyYearSelectV33'),ms=$('historyMonthV33'),unit=$('historyUnitV33');if(ys&&!ys.dataset.ready){var years=B.getAvailableYears();ys.innerHTML='<option value="all">ทั้งหมด</option>'+years.map(function(y){return '<option value="'+y+'">'+y+'</option>'}).join('');ys.dataset.ready='1'}if(ms&&!ms.dataset.ready){ms.innerHTML='<option value="all">ทั้งหมด</option>'+MONTHS.map(function(x,i){return '<option value="'+i+'">'+esc(x)+'</option>'}).join('');ms.dataset.ready='1'}if(unit){unit.innerHTML='<option value="all">ทั้งหมด</option><option value="'+esc(unitName())+'">'+esc(unitName())+'</option>'}}
  function applyFilters(){var q=($('historySearchV24')&&$('historySearchV24').value||'').trim().toLowerCase(),m=$('historyMonthV33')?$('historyMonthV33').value:'all',y=$('historyYearSelectV33')?$('historyYearSelectV33').value:'all',s=$('historyStatusV24')?$('historyStatusV24').value:'all',u=$('historyUnitV33')?$('historyUnitV33').value:'all';filtered=records.filter(function(r){if(m!=='all'&&String(r.month)!==m)return false;if(y!=='all'&&String(r.year)!==y)return false;if(s!=='all'&&r.status!==s)return false;if(u!=='all'&&r.unit!==u)return false;if(q){var hay=[MONTHS[r.month],r.year,r.unit,r.scheduler,r.note,statusLabel(r.status)].join(' ').toLowerCase();if(hay.indexOf(q)<0)return false}return true});page=1;renderAll()}
  function fmt(v){return v?B.formatTime(v):'-'}
  function renderStats(){var total=filtered.length,ap=filtered.filter(function(r){return r.status==='approved'||r.status==='locked'}).length,lk=filtered.filter(function(r){return r.status==='locked'}).length,last=filtered[0];if($('historyTotalV24'))$('historyTotalV24').textContent=total;if($('historyLatestV24'))$('historyLatestV24').textContent=last?(MONTHS[last.month]+' '+last.year):'-';if($('historyLatestDateV33'))$('historyLatestDateV33').textContent=last&&last.savedAt?fmt(last.savedAt):'-';if($('historyApprovedV24'))$('historyApprovedV24').textContent=ap;if($('historyApprovedPctV33'))$('historyApprovedPctV33').textContent=pct(ap,total)+'%';if($('historyLockedV24'))$('historyLockedV24').textContent=lk;if($('historyLockedPctV33'))$('historyLockedPctV33').textContent=pct(lk,total)+'%'}
  function renderRows(){var body=$('historyRowsV33');if(!body)return;var start=(page-1)*pageSize,slice=filtered.slice(start,start+pageSize);body.innerHTML=slice.length?slice.map(function(r,i){return '<tr><td><div class="h33-month-cell"><span class="h33-month-ico">▦</span><span>'+esc(MONTHS[r.month])+' '+r.year+'</span></div></td><td>'+esc(r.unit)+'</td><td><span class="h33-status '+r.status+'">'+(r.status==='locked'?'▣ ':r.status==='approved'?'● ':r.status==='submitted'?'➤ ':'✎ ')+statusLabel(r.status)+'</span></td><td><div class="h33-user"><span class="h33-avatar">👩🏻</span><span>'+esc(r.scheduler)+'</span></div></td><td>'+fmt(r.savedAt)+'</td><td>'+fmt(r.approvedAt)+'</td><td>'+fmt(r.lockedAt)+'</td><td>'+esc(r.note)+'</td><td><button class="h33-open" data-open="'+r.year+'|'+r.month+'">◉ เปิดดู</button><button class="h33-more" data-more="'+r.year+'|'+r.month+'">⋮</button></td></tr>'}).join(''):'<tr><td colspan="9" style="text-align:center;padding:30px;color:#9aa1ad">ไม่พบประวัติการจัดเวรตามตัวกรอง</td></tr>';body.querySelectorAll('[data-open]').forEach(function(b){b.onclick=function(){var p=this.dataset.open.split('|');openRecord(+p[0],+p[1],'roster')}});body.querySelectorAll('[data-more]').forEach(function(b){b.onclick=function(){var p=this.dataset.more.split('|');if(confirm('เปิดตารางสรุปจำนวนเวรของเดือนนี้หรือไม่?'))openRecord(+p[0],+p[1],'summary')}});if($('historyRangeV33'))$('historyRangeV33').textContent='แสดง '+(slice.length?(start+1):0)+' - '+Math.min(start+pageSize,filtered.length)+' จาก '+filtered.length+' รายการ';renderPager()}
  function renderPager(){var host=$('historyPagerV33');if(!host)return;var pages=Math.max(1,Math.ceil(filtered.length/pageSize)),html='<button data-p="prev" '+(page<=1?'disabled':'')+'>‹</button>';for(var p=1;p<=pages;p++){if(p<=5||p===pages||Math.abs(p-page)<=1)html+='<button data-p="'+p+'" class="'+(p===page?'active':'')+'">'+p+'</button>';else if(p===6&&pages>7)html+='<span>…</span>'}html+='<button data-p="next" '+(page>=pages?'disabled':'')+'>›</button>';host.innerHTML=html;host.querySelectorAll('button').forEach(function(b){b.onclick=function(){var v=this.dataset.p;if(v==='prev')page--;else if(v==='next')page++;else page=+v;renderRows()}})}
  function recentKey(){return 'roster_history_recent_v33'}
  function readRecent(){try{return JSON.parse(localStorage.getItem(recentKey())||'[]')}catch(e){return []}}
  function addRecent(y,m){var a=readRecent().filter(function(x){return !(x.year===y&&x.month===m)});a.unshift({year:y,month:m,at:new Date().toISOString()});try{localStorage.setItem(recentKey(),JSON.stringify(a.slice(0,30)))}catch(e){}renderRecent()}
  function openRecord(y,m,type){B.openMonth(y,m,type);addRecent(y,m)}
  function renderRecent(){var host=$('historyRecentV24');if(!host)return;var a=readRecent(),show=(recentAll?a:a.slice(0,5));host.innerHTML=show.length?show.map(function(x){var r=records.find(function(z){return z.year===x.year&&z.month===x.month});return '<div class="h33-recent-item"><span class="h33-list-icon">▦</span><span class="h33-list-main"><b>'+esc(MONTHS[x.month])+' '+x.year+'</b><small>'+esc(r?r.unit:unitName())+'</small></span><span class="h33-list-time">'+fmt(x.at)+' ›</span></div>'}).join(''):'<div style="padding:20px;text-align:center;color:#9aa1ad">ยังไม่มีรายการที่เข้าดูล่าสุด</div>'}
  function allAudit(){var out=[];records.forEach(function(r){var a=r.data&&r.data.workflow&&Array.isArray(r.data.workflow.audit)?r.data.workflow.audit:[];a.forEach(function(x){out.push({x:x,r:r})})});out.sort(function(a,b){return String(b.x.at||'').localeCompare(String(a.x.at||''))});return out}
  function auditStyle(action){var t=String(action||'');if(t.indexOf('ล็อก')>=0)return ['▣','ล็อกตารางเวร','#8866d3'];if(t.indexOf('อนุมัติ')>=0)return ['✓','อนุมัติตารางเวร','#37af86'];if(t.indexOf('ส่ง')>=0)return ['➤','ส่งตรวจตารางเวร','#58a9df'];if(t.indexOf('แก้')>=0)return ['✎','แก้ไขตารางเวร','#ef6698'];return ['✎',t||'บันทึกตารางเวร','#e6a83d']}
  function renderAudit(){var host=$('historyAuditV24');if(!host)return;var a=allAudit(),show=(auditAll?a:a.slice(0,5));host.innerHTML=show.length?show.map(function(z){var st=auditStyle(z.x.action);return '<div class="h33-audit-item"><span class="h33-list-icon" style="color:'+st[2]+'">'+st[0]+'</span><span class="h33-list-main"><b style="color:'+st[2]+'">'+esc(st[1])+'</b><small>'+esc(MONTHS[z.r.month])+' '+z.r.year+' ('+esc(z.r.unit)+') · '+esc(z.x.user||z.r.scheduler)+'</small></span><span class="h33-list-time">'+fmt(z.x.at)+'</span></div>'}).join(''):'<div style="padding:20px;text-align:center;color:#9aa1ad">ยังไม่มี Audit Log</div>'}
  function renderAll(){renderStats();renderRows();renderRecent();renderAudit();if($('historyInfo'))$('historyInfo').textContent='พบ '+filtered.length+' รายการ'}
  function exportCsv(){var rows=[['เดือน/ปี','หน่วยงาน','สถานะ','ผู้จัดเวร','วันที่บันทึก','วันที่อนุมัติ','วันที่ล็อก','หมายเหตุ']];filtered.forEach(function(r){rows.push([MONTHS[r.month]+' '+r.year,r.unit,statusLabel(r.status),r.scheduler,fmt(r.savedAt),fmt(r.approvedAt),fmt(r.lockedAt),r.note])});var csv='\ufeff'+rows.map(function(row){return row.map(function(v){return '"'+String(v||'').replace(/"/g,'""')+'"'}).join(',')}).join('\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='ประวัติการจัดเวร.csv';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
  function resetFilters(){if($('historySearchV24'))$('historySearchV24').value='';if($('historyMonthV33'))$('historyMonthV33').value='all';if($('historyYearSelectV33'))$('historyYearSelectV33').value='all';if($('historyStatusV24'))$('historyStatusV24').value='all';if($('historyUnitV33'))$('historyUnitV33').value='all';applyFilters()}
  function wire(){setupFilters();buildRecords();filtered=records.slice();renderAll();['historyMonthV33','historyYearSelectV33','historyStatusV24','historyUnitV33'].forEach(function(id){var e=$(id);if(e)e.onchange=applyFilters});if($('historySearchV24'))$('historySearchV24').oninput=applyFilters;if($('historyRefreshBtn'))$('historyRefreshBtn').onclick=function(){buildRecords();applyFilters()};if($('historyResetV33'))$('historyResetV33').onclick=resetFilters;if($('historyExportV33'))$('historyExportV33').onclick=exportCsv;if($('historyPageSizeV33'))$('historyPageSizeV33').onchange=function(){pageSize=+this.value||5;page=1;renderRows()};if($('historyRecentAllV33'))$('historyRecentAllV33').onclick=function(){recentAll=!recentAll;this.textContent=recentAll?'ย่อรายการ':'ดูทั้งหมด';renderRecent()};if($('historyAuditAllV33'))$('historyAuditAllV33').onclick=function(){auditAll=!auditAll;this.textContent=auditAll?'ย่อรายการ':'ดูทั้งหมด';renderAudit()};if($('historyCloseViewerBtn'))$('historyCloseViewerBtn').onclick=function(){var v=$('historyViewer');if(v)v.classList.remove('show')}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
  window.addEventListener('pageshow',function(){setTimeout(function(){buildRecords();applyFilters()},50)});
})();
